version: "3.3"
   
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nothing
      - POSTGRES_USER=hieucao192
      - POSTGRES_PASSWORD=192
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=nothing
      - DB_USER=hieucao192
      - DB_PASS=192
    depends_on:
      - db
