# Generated by Django 3.2.4 on 2021-08-26 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import findTutor.validators
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('number_of_identity_card', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('province_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_province])),
                ('district_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_district])),
                ('ward_code', models.IntegerField(blank=True, default=1, null=True, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward])),
                ('detail_location', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_province])),
                ('district_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_district])),
                ('ward_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward])),
                ('detail_location', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=200)),
                ('lop', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)])),
                ('isTeaching', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('day_can_teach', multiselectfield.db.fields.MultiSelectField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], max_length=13)),
                ('other_require', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_identity_card', models.CharField(blank=True, max_length=200, null=True)),
                ('number_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('province_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_province])),
                ('district_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_district])),
                ('ward_code', models.IntegerField(blank=True, default=1, null=True, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward])),
                ('detail_location', models.CharField(blank=True, max_length=500, null=True)),
                ('profession', models.CharField(choices=[('sv', 'SINH_VIEN'), ('gv', 'GIAO_VIEN')], max_length=10)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('achievement', models.TextField(blank=True, null=True)),
                ('lop_day', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'lop_1'), (2, 'lop_2'), (3, 'lop_3'), (4, 'lop_4'), (5, 'lop_5'), (6, 'lop_6'), (7, 'lop_7'), (8, 'lop_8'), (9, 'lop_9'), (10, 'lop_10'), (11, 'lop_11'), (12, 'lop_12'), (13, 'nam_1'), (14, 'nam_2'), (15, 'nam_3'), (16, 'nam_4'), (17, 'nam_5')], max_length=41)),
                ('khu_vuc_day', models.TextField(blank=True, null=True)),
                ('cap_day', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'cap_1'), (2, 'cap_2'), (3, 'cap_3'), (4, 'dai_hoc')], max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingTutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('time_expired', models.BooleanField(default=False)),
                ('parent_invite', models.BooleanField(default=False)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='TutorTeachingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('parent_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='TryTeachingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_agree', models.BooleanField(default=False)),
                ('parent_agree', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('time_expired', models.BooleanField(default=False)),
                ('parent_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_one_day', models.DecimalField(decimal_places=1, max_digits=2)),
                ('money', models.IntegerField()),
                ('time_price_pay_for', models.CharField(choices=[('buoi', 'BUOI'), ('tieng', 'TIENG')], max_length=20)),
                ('teacher', models.CharField(choices=[('sv', 'Sinh Vien'), ('gv', 'Giao Vien')], max_length=20)),
                ('sex_of_teacher', multiselectfield.db.fields.MultiSelectField(choices=[('nu', 'NU'), ('nam', 'NAM')], max_length=6)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
            ],
        ),
        migrations.CreateModel(
            name='OldLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_province])),
                ('district_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_district])),
                ('ward_code', models.IntegerField(default=1, null=True, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward])),
                ('detail_location', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListInvitedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_agree', models.BooleanField(default=False)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePrivateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('identity_card', models.ImageField(blank=True, null=True, upload_to='identity_card/')),
                ('student_card', models.ImageField(blank=True, null=True, upload_to='student_card/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_image/')),
                ('type_of_image', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
