# Generated by Django 3.2.4 on 2021-07-29 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifiedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('lop', models.IntegerField(choices=[(1, 'lop_1'), (2, 'lop_2'), (3, 'lop_3'), (4, 'lop_4'), (5, 'lop_5'), (6, 'lop_6'), (7, 'lop_7'), (8, 'lop_8'), (9, 'lop_9'), (10, 'lop_10'), (11, 'lop_11'), (12, 'lop_12'), (13, 'nam_1'), (14, 'nam_2'), (15, 'nam_3'), (16, 'nam_4'), (17, 'nam_5')])),
                ('isTeaching', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('day_can_teach', multiselectfield.db.fields.MultiSelectField(choices=[(2, 'thu_2'), (3, 'thu_3'), (4, 'thu_4'), (5, 'thu_5'), (6, 'thu_6'), (7, 'thu_7'), (8, 'chu_nhat')], max_length=13)),
                ('other_require', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPrimaryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('identity_card', models.ImageField(upload_to='')),
                ('number_phone', models.CharField(max_length=30)),
                ('number_of_identity_card', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('userprimaryinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='findTutor.userprimaryinformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('findTutor.userprimaryinformation',),
        ),
        migrations.CreateModel(
            name='TutorModel',
            fields=[
                ('userprimaryinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='findTutor.userprimaryinformation')),
                ('profession', models.CharField(choices=[('sv', 'SINH_VIEN'), ('gv', 'GIAO_VIEN')], max_length=10)),
                ('university', models.CharField(max_length=200)),
                ('experience', models.TextField()),
                ('achievement', models.TextField()),
                ('cap_day', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'cap_1'), (2, 'cap_2'), (3, 'cap_3'), (4, 'dai_hoc')], max_length=7)),
                ('lop_day', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'lop_1'), (2, 'lop_2'), (3, 'lop_3'), (4, 'lop_4'), (5, 'lop_5'), (6, 'lop_6'), (7, 'lop_7'), (8, 'lop_8'), (9, 'lop_9'), (10, 'lop_10'), (11, 'lop_11'), (12, 'lop_12'), (13, 'nam_1'), (14, 'nam_2'), (15, 'nam_3'), (16, 'nam_4'), (17, 'nam_5')], max_length=41)),
                ('khu_vuc_day', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('findTutor.userprimaryinformation',),
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_one_day', models.DecimalField(decimal_places=1, max_digits=2)),
                ('money', models.IntegerField()),
                ('time_price_pay_for', models.CharField(choices=[('buoi', 'BUOI'), ('tieng', 'TIENG')], max_length=20)),
                ('teacher', models.CharField(choices=[('sv', 'Sinh Vien'), ('gv', 'Giao Vien')], max_length=20)),
                ('sex_of_teacher', multiselectfield.db.fields.MultiSelectField(choices=[('nu', 'NU'), ('nam', 'NAM')], max_length=6)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingTutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('time_expired', models.BooleanField(default=False)),
                ('parent_invite', models.BooleanField(default=False)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='TutorTeachingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('parent_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='TryTeachingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_agree', models.BooleanField(default=False)),
                ('parent_agree', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('time_expired', models.BooleanField(default=False)),
                ('parent_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.AddField(
            model_name='parentroommodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentmodel'),
        ),
        migrations.CreateModel(
            name='NotifiedTutorModel',
            fields=[
                ('notifiedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='findTutor.notifiedmodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
            bases=('findTutor.notifiedmodel',),
        ),
        migrations.CreateModel(
            name='NotifiedParentModel',
            fields=[
                ('notifiedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='findTutor.notifiedmodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentmodel')),
            ],
            bases=('findTutor.notifiedmodel',),
        ),
        migrations.CreateModel(
            name='ListInvitedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_agree', models.BooleanField(default=False)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentAboutTutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentmodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
    ]
