# Generated by Django 3.2.4 on 2021-08-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='identity_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_card/'),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='identity_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_card/'),
        ),
    ]
