# Generated by Django 3.2.4 on 2021-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0002_auto_20210801_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentroommodel',
            name='location',
        ),
        migrations.AddField(
            model_name='parentroommodel',
            name='district_code',
            field=models.IntegerField(default=1, max_length=973),
        ),
        migrations.AddField(
            model_name='parentroommodel',
            name='province_code',
            field=models.IntegerField(default=1, max_length=96),
        ),
        migrations.AddField(
            model_name='parentroommodel',
            name='ward_code',
            field=models.IntegerField(default=1, max_length=32248),
        ),
    ]
