# Generated by Django 3.2.4 on 2021-08-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0002_auto_20210812_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmodel',
            name='number_of_identity_card',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='number_of_identity_card',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
