# Generated by Django 3.2.4 on 2021-07-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0002_alter_waitingtutormodel_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingtutormodel',
            name='parent_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitingtutormodel',
            name='tutor_agree',
            field=models.BooleanField(default=False),
        ),
    ]
