# Generated by Django 3.2.4 on 2021-07-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0003_auto_20210716_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryTeachingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_agree', models.BooleanField(default=False)),
                ('parent_agree', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('time_expired', models.BooleanField(default=False)),
                ('parent_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
        migrations.CreateModel(
            name='ListInvitedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_agree', models.BooleanField(default=False)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
        ),
    ]
