# Generated by Django 3.2.4 on 2021-08-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0004_oldimageprivateusermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageofusermodel',
            old_name='type_of_image',
            new_name='type_image',
        ),
    ]
