# Generated by Django 3.2.4 on 2021-08-19 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import findTutor.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findTutor', '0004_alter_parentroommodel_day_can_teach'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_image/')),
                ('type_of_image', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePrivateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('identity_card', models.ImageField(blank=True, null=True, upload_to='identity_card/')),
                ('student_card', models.ImageField(blank=True, null=True, upload_to='student_card/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='parentmodel',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='parentmodel',
            name='identity_card',
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='identity_card',
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='detail_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='number_of_identity_card',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='number_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='ward_code',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward]),
        ),
        migrations.AlterField(
            model_name='parentroommodel',
            name='lop',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)]),
        ),
        migrations.AlterField(
            model_name='parentroommodel',
            name='other_require',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentroommodel',
            name='ward_code',
            field=models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward]),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='achievement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='detail_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='khu_vuc_day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='number_of_identity_card',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='number_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='profession',
            field=models.CharField(choices=[('sv', 'SINH_VIEN'), ('gv', 'GIAO_VIEN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='ward_code',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward]),
        ),
        migrations.DeleteModel(
            name='ImageOfTutor',
        ),
    ]
