# Generated by Django 3.2.4 on 2021-07-17 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0004_listinvitedmodel_tryteachingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingtutormodel',
            name='parent_invite',
        ),
        migrations.RemoveField(
            model_name='waitingtutormodel',
            name='tutor_agree',
        ),
        migrations.AddField(
            model_name='tutorteachingmodel',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
