# Generated by Django 3.2.4 on 2021-08-02 13:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0004_auto_20210802_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodel',
            name='cap_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'cap_1'), (2, 'cap_2'), (3, 'cap_3'), (4, 'dai_hoc')], default=[2], max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='lop_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'lop_1'), (2, 'lop_2'), (3, 'lop_3'), (4, 'lop_4'), (5, 'lop_5'), (6, 'lop_6'), (7, 'lop_7'), (8, 'lop_8'), (9, 'lop_9'), (10, 'lop_10'), (11, 'lop_11'), (12, 'lop_12'), (13, 'nam_1'), (14, 'nam_2'), (15, 'nam_3'), (16, 'nam_4'), (17, 'nam_5')], default=[2], max_length=41),
            preserve_default=False,
        ),
    ]
