# Generated by Django 3.2.4 on 2021-08-03 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import findTutor.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findTutor', '0005_auto_20210802_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentroommodel',
            name='detail_location',
            field=models.CharField(default='Ha noi', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentroommodel',
            name='ward_code',
            field=models.IntegerField(default=1, null=True, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward]),
        ),
        migrations.AlterField(
            model_name='userprimaryinformation',
            name='ward_code',
            field=models.IntegerField(default=1, null=True, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward]),
        ),
        migrations.CreateModel(
            name='OldLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_province])),
                ('district_code', models.IntegerField(default=1, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_district])),
                ('ward_code', models.IntegerField(default=1, null=True, validators=[findTutor.validators.min_code_of_location, findTutor.validators.max_code_of_ward])),
                ('detail_location', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
