# Generated by Django 3.2.4 on 2021-07-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0005_auto_20210717_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingtutormodel',
            name='parent_invite',
            field=models.BooleanField(default=False),
        ),
    ]
