# Generated by Django 3.2.4 on 2021-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0005_rename_type_of_image_imageofusermodel_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldimageprivateusermodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
