# Generated by Django 3.2.4 on 2021-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0006_auto_20210803_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprimaryinformation',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='userprimaryinformation',
            name='identity_card',
            field=models.ImageField(null=True, upload_to='identity_card/'),
        ),
    ]
