# Generated by Django 3.2.4 on 2021-08-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0006_alter_oldimageprivateusermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldimageprivateusermodel',
            name='type_action',
            field=models.CharField(choices=[('update', 'update'), ('delete', 'delete')], default='update', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oldimageprivateusermodel',
            name='type_image',
            field=models.CharField(choices=[('avatar', 'avatar'), ('identity_card', 'identity_card'), ('student_card', 'student_card')], max_length=200),
        ),
    ]
