# Generated by Django 3.2.4 on 2021-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0007_auto_20210828_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprivateusermodel',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprivateusermodel',
            name='identity_card',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprivateusermodel',
            name='student_card',
            field=models.TextField(blank=True, null=True),
        ),
    ]
