# Generated by Django 3.2.4 on 2021-08-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0009_auto_20210805_0406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentAboutTutorModel',
        ),
    ]
