# Generated by Django 3.2.4 on 2021-08-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0010_imageofusermodel_is_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageofusermodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
