# Generated by Django 3.2.4 on 2021-09-06 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0014_alter_parentroommodel_detail_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorteachingmodel',
            old_name='start_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='waitingtutormodel',
            old_name='join_at',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='listinvitedmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
