# Generated by Django 3.2.4 on 2021-09-06 16:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0015_auto_20210906_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodel',
            name='cap_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=7),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='lop_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)], max_length=41),
        ),
    ]
