# Generated by Django 3.2.4 on 2021-09-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0018_auto_20210908_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricemodel',
            old_name='teacher',
            new_name='type_teacher',
        ),
    ]
