# Generated by Django 3.2.4 on 2021-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0020_tutormodel_mon_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmodel',
            name='subject_care',
            field=models.TextField(blank=True, null=True),
        ),
    ]
