# Generated by Django 3.2.4 on 2021-09-17 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0022_auto_20210911_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryteachingmodel',
            name='parent_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel'),
        ),
    ]
