# Generated by Django 3.2.4 on 2021-11-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0023_alter_tryteachingmodel_parent_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentmodel',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='tutormodel',
            name='birthday',
        ),
    ]
