# Generated by Django 3.2.4 on 2021-11-02 07:15

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0024_auto_20211102_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 11, 2, 7, 15, 13, 173817, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutormodel',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
