# Generated by Django 3.2.4 on 2021-11-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findTutor', '0026_alter_parentroommodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldlocationmodel',
            options={'permissions': (('delete_room', 'Can delete a room'),)},
        ),
        migrations.AlterModelOptions(
            name='parentroommodel',
            options={'permissions': (('delete_room', 'Can delete a room'),)},
        ),
    ]
