# Generated by Django 3.2.4 on 2021-08-07 14:07

import comment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findTutor', '0011_auto_20210807_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAboutTutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.tutormodel')),
            ],
            bases=(models.Model, comment.models.CommentBaseMode),
        ),
        migrations.CreateModel(
            name='CommentAboutParentRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentroommodel')),
            ],
            bases=(models.Model, comment.models.CommentBaseMode),
        ),
        migrations.CreateModel(
            name='CommentAboutParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findTutor.parentmodel')),
            ],
            bases=(models.Model, comment.models.CommentBaseMode),
        ),
    ]
