# Generated by Django 3.2.4 on 2021-08-14 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAboutUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('about_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_user', to=settings.AUTH_USER_MODEL)),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.commentaboutusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentabouttutormodel',
            name='about_who',
        ),
        migrations.RemoveField(
            model_name='commentabouttutormodel',
            name='belong_to',
        ),
        migrations.RemoveField(
            model_name='commentabouttutormodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentAboutParentModel',
        ),
        migrations.DeleteModel(
            name='CommentAboutTutorModel',
        ),
    ]
